version: "3.7"

services:
  app:
    build:
      args:
        user: quanbt
        uid: 1000
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: crawl-data-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      CONTAINER_ROLE: app
    networks:
      - crawl-app
  scheduler:
    image: craw-data-image
    container_name: laravel-scheduler
    depends_on:
      - app
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
  db:
    image: mysql:8.0
    container_name: crawl-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - crawl-app

  nginx:
    image: nginx:1.17-alpine
    container_name: crawl-data-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - crawl-app
networks:
  crawl-app:
    driver: bridge
