version: "3.7"

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: crawl-data-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - crawl-app

  nginx:
    image: nginx:1.17-alpine
    container_name: crawl-data-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - crawl-app
networks:
  crawl-app:
    driver: bridge
